server:
  port: 8080 # 服务端口号

logging:
  level:
    root: warn #一般日志级别: error, warn, info, debug, trace
    #    静默通知
    com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean: INFO #mybatis-plus SQL执行日志: INFO级别

spring:
  main:
    banner-mode: off # 关闭启动时的图标
    allow-bean-definition-overriding: true #允许覆盖bean定义
  
  application:
    name: sk_take_out # 应用名称
  
  #  #  本地数据库配置4要素 名字: takeout
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  #    username: root
  #    password: 2333
  #    #    连接池配置(与旧版本不同)
  #    type: com.alibaba.druid.pool.DruidDataSource
  
  #  热部署:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    livereload:
      enabled: true
  
  thymeleaf:
    cache: false #使用Thymeleaf模板引擎，关闭缓存
  
  jpa:
    open-in-view: false #禁止延迟加载，避免出现懒加载异常
  
  cache:
    redis: #Redis配置(与旧版本不同)
      time-to-live: 1800000 #设置缓存数据的过期时间=30min(不必要)
  
  data:
    redis: #Redis配置(与旧版本不同)
      host: 192.168.91.129 # Master
      password: root@2333
      database: 0
      port: 6379
  
  shardingsphere: #分库分表配置
    datasource: #本地虚拟机数据库配置
      names:
        master,slave #只是名字

      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.91.129:3306/takeout?characterEncoding=utf-8
        username: root
        password: 2333
      
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.91.130:3306/takeout?characterEncoding=utf-8
        username: root
        password: 2333
    
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    
    props:
      sql:
        show: true #开启SQL显示，默认false



mybatis-plus:
  configuration:
    
    call-setters-on-nulls: true #查询结果为null时调用setter方法，防止字段为null时报错
    map-underscore-to-camel-case: true #开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #日志打印:取消Parsed-mapper-file日志打印
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印完整带参数SQL语句
  
  # 这里根据自己项目的包修改，扫描到自己的*xml文件
  mapper-locations: classpath:mapper/*.xml

  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: off #关闭mybatis-plus启动图标


resources:
  path: D:\img\ #图片存储路径
